CREATE DATABASE BD_ESCOLA;
USE BD_ESCOLA;

CREATE TABLE  ALUNOS(
USER_ID_ALUNO INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
IDADE INT(3) ,
NOTA1 FLOAT NOT NULL ,
NOTA2 FLOAT NOT NULL,
MEDIA FLOAT NOT NULL,
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ALTERACAO DATETIME DEFAULT NOW()
);